name: Build TB-303 Emulator

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libasound2-dev libjack-jackd2-dev pkg-config libfreetype6-dev libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev
    
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        # Xcode command line tools are already installed on GitHub runners
        echo "macOS dependencies ready"
    
    - name: Setup Windows environment
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }} --parallel
    
    - name: Package plugins
      shell: bash
      run: |
        mkdir -p packages
        cd build/TB303Emulator_artefacts/${{ matrix.build_type }}
        
        if [ "${{ runner.os }}" == "Windows" ]; then
          # Windows: Create ZIP with VST3 and Standalone using PowerShell
          powershell -Command "Compress-Archive -Path VST3/, Standalone/ -DestinationPath ../../../packages/TB303Emulator-Windows-${{ matrix.build_type }}.zip"
        elif [ "${{ runner.os }}" == "macOS" ]; then
          # macOS: Create ZIP with VST3, AU (if exists), and Standalone
          if [ -d "AU" ]; then
            zip -r ../../../packages/TB303Emulator-macOS-${{ matrix.build_type }}.zip VST3/ AU/ Standalone/
          else
            zip -r ../../../packages/TB303Emulator-macOS-${{ matrix.build_type }}.zip VST3/ Standalone/
          fi
        else
          # Linux: Create tar.gz with VST3 and Standalone
          tar -czf ../../../packages/TB303Emulator-Linux-${{ matrix.build_type }}.tar.gz VST3/ Standalone/
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TB303Emulator-${{ runner.os }}-${{ matrix.build_type }}
        path: packages/
        retention-days: 30

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/**/*.zip
          artifacts/**/*.tar.gz
        body: |
          ## TB-303 Emulator Release ${{ github.ref_name }}
          
          ### Downloads
          - **Windows**: Download the `.zip` file and extract to your VST3 folder
          - **macOS**: Download the `.zip` file and extract VST3/AU to your plugin folders  
          - **Linux**: Download the `.tar.gz` file and extract to your VST3 folder
          
          ### Installation
          - **Windows**: `C:\Program Files\Common Files\VST3\`
          - **macOS VST3**: `~/Library/Audio/Plug-Ins/VST3/`
          - **macOS AU**: `~/Library/Audio/Plug-Ins/Components/`
          - **Linux**: `~/.vst3/` or `/usr/lib/vst3/`
          
          ### What's New
          See the commit history for detailed changes in this release.
        draft: false
        prerelease: false