name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
      release_notes:
        description: 'Release notes'
        required: false
        default: 'Bug fixes and improvements'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Get current version
      id: current_version
      run: |
        CURRENT_VERSION=$(grep "project(TB303Emulator VERSION" CMakeLists.txt | sed 's/.*VERSION \([0-9.]*\).*/\1/')
        echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
    
    - name: Calculate new version
      id: new_version
      run: |
        CURRENT="${{ steps.current_version.outputs.current }}"
        TYPE="${{ github.event.inputs.version_type }}"
        
        IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT"
        MAJOR=${VERSION_PARTS[0]}
        MINOR=${VERSION_PARTS[1]}
        PATCH=${VERSION_PARTS[2]}
        
        case $TYPE in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH + 1))
            ;;
        esac
        
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version will be: $NEW_VERSION"
    
    - name: Update version in CMakeLists.txt
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.version }}"
        sed -i "s/project(TB303Emulator VERSION [0-9.]*/project(TB303Emulator VERSION $NEW_VERSION/" CMakeLists.txt
    
    - name: Commit and tag
      run: |
        NEW_VERSION="${{ steps.new_version.outputs.version }}"
        RELEASE_NOTES="${{ github.event.inputs.release_notes }}"
        
        git add CMakeLists.txt
        git commit -m "Bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release $NEW_VERSION

$RELEASE_NOTES"
        
        git push origin main
        git push origin "v$NEW_VERSION"